/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 12 02:43:57 GMT 2020
 */

package org.jsoup.parser;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.parser.ParseError;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ParseError_ESTest extends ParseError_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Object[] objectArray0 = new Object[3];
      ParseError parseError0 = new ParseError(0, "{J+PL=*.@13TWec=k5", objectArray0);
      parseError0.toString();
      assertEquals(0, parseError0.getPosition());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Object[] objectArray0 = new Object[3];
      ParseError parseError0 = new ParseError(0, "{J+PL=*.@13TWec=k5", objectArray0);
      parseError0.getErrorMessage();
      assertEquals(0, parseError0.getPosition());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Object[] objectArray0 = new Object[3];
      ParseError parseError0 = new ParseError(0, "{J+PL=*.@13TWec=k5", objectArray0);
      int int0 = parseError0.getPosition();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ParseError parseError0 = new ParseError(0, "$H}1jb)x1'LNUSqw}27");
      assertEquals(0, parseError0.getPosition());
  }
}
