/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 12 02:28:31 GMT 2020
 */

package org.jsoup;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.HttpStatusException;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class HttpStatusException_ESTest extends HttpStatusException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      HttpStatusException httpStatusException0 = new HttpStatusException("o7C2j+UGwrENBkb", 1123, "o7C2j+UGwrENBkb");
      String string0 = httpStatusException0.toString();
      assertEquals("org.evosuite.runtime.mock.java.lang.MockThrowable: o7C2j+UGwrENBkb. Status=1123, URL=o7C2j+UGwrENBkb", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      HttpStatusException httpStatusException0 = new HttpStatusException("o7C2j+UGwrENBkb", 1123, "o7C2j+UGwrENBkb");
      int int0 = httpStatusException0.getStatusCode();
      assertEquals(1123, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      HttpStatusException httpStatusException0 = new HttpStatusException("o7C2j+UGwrENBkb", 1123, "o7C2j+UGwrENBkb");
      String string0 = httpStatusException0.getUrl();
      assertEquals("o7C2j+UGwrENBkb", string0);
  }
}
