/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 12 02:26:31 GMT 2020
 */

package org.jsoup;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.File;
import java.io.FileNotFoundException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.jsoup.Jsoup;
import org.jsoup.safety.Whitelist;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Jsoup_ESTest extends Jsoup_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = "S-bU4L<xowcPtr<;Q";
      MockFile mockFile0 = new MockFile("S-bU4L<xowcPtr<;Q");
      try { 
        Jsoup.parse((File) mockFile0, string0);
        fail("Expecting exception: FileNotFoundException");
      
      } catch(FileNotFoundException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Whitelist whitelist0 = new Whitelist();
      String string0 = Jsoup.clean("SKIP_ENTIRELY", whitelist0);
      assertEquals("SKIP_ENTIRELY", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Jsoup.parseBodyFragment("");
  }
}
